language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo test --lib
  - RUST_LOG=actix_raft,clustering=debug cargo test clustering
  - RUST_LOG=actix_raft,client_writes=debug cargo test client_writes
  - RUST_LOG=actix_raft,snapshotting=debug cargo test snapshotting
