language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo test
  - cargo install --vers "^0.3" mdbook && mdbook build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_PAGES_TOKEN
  keep_history: false
  local_dir: guide/book
  target_branch: gh-pages
  on:
    branch: master
