language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)

script:
  # - mdbook build && mdbook test # TODO: fix the mdbook test errors.
  - mdbook build
  # - cargo test
  # - cargo test --release

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_PAGES_TOKEN
  keep_history: false
  local_dir: guide/book
  target_branch: gh-pages
  on:
    branch: master
