[package]
name = "actix-raft"
version = "0.1.0"
authors = ["Anthony Dodd <dodd.anthonyjosiah@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.8"
bytes = "0.4"
futures = "0.1"
log = "0.4"
prost = "0.5"
prost-derive = "0.5"
rand = "0.6"
rmp-serde = "0.13"
serde = { version="1", features=["derive"] }
tokio = "0.1"

[build-dependencies]
prost-build = "0.5"

[dev-dependencies]
tempfile = "3"
env_logger = "0.6"
